# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FSPagerView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSPagerView
      pod 'Nuke-FLAnimatedImage-Plugin'
          pod 'Nuke', '~> 7.5.1'



end
